platform :ios, '9.0'
use_frameworks!

target 'ISDKTest' do

  # pod 'R.swift', '~> 5.1.0'
  # pod 'RealmSwift', '~> 3.11.1'
  # pod 'SwiftLint', '~> 0.37.0'
  pod 'Swinject', '~> 2.7.1'
  # pod 'RxSwift', '~> 4.4.0'
  # pod 'RxCocoa', '~> 4.4.0'
  # pod 'RxRealm', '~> 0.7.6'
  pod 'SteviaLayout', '~> 4.7.2'
  
end
